PANEL:
  DEVICE:
    WIDTH: 1072
    HEIGHT: 1448
  UPDATE:
    INTERVAL: 120

INFLUXDB:
  URL: http://proxy.green-rabbit.net:8086
  TOKEN: dummy
  ORG: home
  BUCKET: sensor

USAGE:
  WIDTH: 1072
  HEIGHT: 400
  TARGET:
    HOST: テレビ
    TYPE: hems.sharp
    PARAM: power
    THRESHOLD:
      WAKE: 20
      WORK: 60

GRAPH:
  WIDTH: 1072
  HEIGHT: 1418
  OFFSET: 30
  EQUIP_LIST:
    - HOST: テレビ
      TYPE: hems.sharp
      RANGE:
        - 0
        - 160
      SHOW_VALUE: False
    - LABEL: リビング
      HOST: リビングエアコン
      TYPE: hems.sharp
    - LABEL: 和室
      HOST: 和室エアコン
      TYPE: hems.sharp
    - LABEL: 書斎
      HOST: 書斎エアコン
      TYPE: hems.sharp
  VALVE:
    HOST: rasp-cooler
    TYPE: sensor.rasp
    PARAM: flow
    THRESHOLD:
      INTERM: 0.05
      FULL: 0.3

  PARAM:
    NAME: power
    FORMAT: '{:,.0f}'
    UNIT: 'W'
    RANGE:
      - 0
      - 1500
    PERIOD: '48h'
    SIZE_SMALL: False

ICON:
  PATH: ../icon/ # スクリプトのフォルダからの相対パス
  MAP:
    TV: tv.png
    AIRCON: aircon.png

FONT:
  PATH: ../font/ # スクリプトのフォルダからの相対パス
  MAP:
    JP_REGULAR: migmix-1p-regular.ttf
    JP_MEDIUM: migmix-1p-regular.ttf
    JP_BOLD: migmix-1p-bold.ttf

    EN_COND_BOLD: Antonio-Bold.ttf
    EN_COND: Antonio-Regular.ttf

    EN_MEDIUM: migmix-1p-regular.ttf
    EN_BOLD: migmix-1p-bold.ttf
    EN_HEAVY: migmix-1p-bold.ttf

    # JP_REGULAR: A-OTF-UDShinGoPr6N-Regular.otf
    # JP_MEDIUM: A-OTF-UDShinGoPr6N-Medium.otf
    # JP_BOLD: A-OTF-UDShinGoPr6N-Bold.otf
    # EN_COND_BOLD: FuturaStd-CondensedBold.otf
    # EN_COND: FuturaStd-Condensed.otf
    # EN_MEDIUM: FuturaStd-Medium.otf
    # EN_BOLD: FuturaStd-Bold.otf
    # EN_HEAVY: FuturaStd-Heavy.otf


LIVENESS:
  FILE: /dev/shm/healthz
